name: calculate coverage
on:
  push:
    branches:
      - master

jobs:
  # Calculates new coverage for the base branch
  calc_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          python-version: "3.10"
          activate-environment: test
          environment-file: .github/test_conda_env.yml
          condarc-file: .github/test_condarc.yml

      - name: install
        shell: bash -l {0}
        run: |
          pip install -e .

      - name: run test suite
        shell: bash -l {0}
        run: |
          pytest -s --cov dbscan1d --cov-report=xml

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
