name: release
on:
  release:
    types:
      - published

jobs:
  publish_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "get tags"
        run: |
          git fetch --tags --force # Retrieve annotated tags.

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.12

      - name: install
        shell: bash -l {0}
        run: |
          pip install -e .[dev]

      - name: create dists
        shell: bash -l {0}
        run: |
          python -m pip install build
          python -m build

      - name: publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
