name: release
on:
  release:
    types:
      - published

jobs:
  publish_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          python-version: "3.11"
          activate-environment: test
          environment-file: .github/test_conda_env.yml
          condarc-file: .github/test_condarc.yml

      - name: install
        shell: bash -l {0}
        run: |
          pip install -e .[dev]

      - name: create dists
        shell: bash -l {0}
        run: |
          python -m pip install build
          python -m build

      - name: publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
